name: Continuous Integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  pipeline:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-dotnet@main
        with:
            dotnet-version: '5.0'

      - name: Build Solution
        run: dotnet build --configuration Release
      
      - name: Run Tests
        run: dotnet test
      
      - name: Create Package
        run: dotnet pack Kalon --configuration Release
      
      - uses: actions/setup-dotnet@main
        with:
            dotnet-version: '5.0'
            source-url: https://nuget.pkg.github.com/${{github.actor}}
        env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish Package
        run: dotnet nuget push 'Kalon\bin\Release\*.nupkg' --skip-duplicate
